name: Docker Image CI

on:
  release:
    types: [created]
  workflow_dispatch:
      
env:
  IMAGE_NAME_ELASTIC: elasticsearch-dd:7.6.0
  IMAGE_NAME_OPENDISTRO: opendistro-elasticsearch-dd:7.10.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image elasticsearch
      run: docker build ./elasticsearch --tag docker.pkg.github.com/digdes/$IMAGE_NAME_ELASTIC
    - name: Log into GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u DigDes --password-stdin docker.pkg.github.com
    - name: Push image to GitHub Container Registry
      run: docker push docker.pkg.github.com/digdes/$IMAGE_NAME_ELASTIC
      
      
