name: Docker Image CI

on:
  release:
    types: [created]
  workflow_dispatch:
      
env:
  IMAGE_NAME_ELASTIC: elasticsearch-dd:7.6.0
  IMAGE_NAME_OPENDISTRO: opendistro-elasticsearch-dd:1.13.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image elasticsearch
      run: docker build ./elasticsearch --tag ghcr.io/digdes/$IMAGE_NAME_ELASTIC
    - name: Build the Docker image opendistro elasticsearch
      run: docker build ./opendistro-elasticsearch --tag ghcr.io/digdes/$IMAGE_NAME_OPENDISTRO
    - name: Log into GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u DigDes --password-stdin ghcr.io
    - name: Push elasticsearch image to GitHub Container Registry
      run: docker push ghcr.io/digdes/$IMAGE_NAME_ELASTIC
    - name: Push opendistro elasticsearch image to GitHub Container Registry
      run: docker push ghcr.io/digdes/$IMAGE_NAME_OPENDISTRO
      
      
